### ISSUE TITLE
bovigo\assert\assert() not executed when zend.assertions not set to 1

### ISSUE THREAD

**Issue by eigan** [mikey179/bovigo-assert#7]
Hello!

This is a followup to mikey179/vfsStream#160. 

https://gist.github.com/eigan/fde3fea431b190111219df65ee506b6a

**Comment by eigan** [comment]
`phpunit --dont-report-useless-tests` is how one can ignore these risky stuff, but I cant see that mentioned in Travis configuration.

**Comment by eigan** [comment]
Looks like [Travis is just testing 2.2, where phpunit is not > 6.0](https://travis-ci.org/mikey179/bovigo-assert/jobs/277831438)?

https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-6.0.0
> PHPUnit is now strict about useless tests by default. Use the --dont-report-useless-tests commandline option or the beStrictAboutTestsThatDoNotTestAnything="false" configuration directive to disable this risky test check.

**Comment by mikey179** [comment]
The problem is with the `zend.assertions` ini directive. When it is set to 0 PHP will not execute the `assert()` function. Since [PHP 7.0 `assert` is a language construct](http://php.net/assert) - I wonder why it's still possible to define such a function. I think this behaviour is buggy within PHP, as it still should execute the user defined function when it allows to define one with such a name. But I guess I have to define an alternative function to get around this issue...

**Comment by eigan** [comment]
FYI my ini configuration is:
```
$ php -i | grep assert

zend.assertions => -1 => -1
assert.active => 1 => 1
assert.bail => 0 => 0
assert.callback => no value => no value
assert.exception => 0 => 0
assert.quiet_eval => 0 => 0
assert.warning => 1 => 1
```

**Comment by mikey179** [comment]
Most likely `zend.assertions=-1` is the culprit here. With `zend.assertions=0` PHP generates the code but jumps around it, with `zend.assertions=-1` it doesn't even generate the code. Only with `zend.assertions=1` the `bovigo\assert\assert()`function is executed. With vfsStream I experienced that on AppVeyor:
* [Test run with zend.assertions=0 or -1](https://ci.appveyor.com/project/mikey179/vfsstream/build/1.0.46)
* [Test run with zend.assertions=1](https://ci.appveyor.com/project/mikey179/vfsstream/build/1.0.47).

I'm still stuck trying to create a small reproducible phpt version, but I'm pretty sure it depends on the zend.assertions setting. I'm also pretty sure that the PHP behaviour in regard to user-defined function assert() is buggy, but without a small reproducable test I don't want to open an issue.

**Comment by mikey179** [comment]
While I failed @kelunik managed to create a reproducible test case, so there's now a [PHP bug open](https://bugs.php.net/bug.php?id=75445).

**Comment by mikey179** [comment]
PHP bug has been closed, as it is [expected behaviour according to the RFC](https://wiki.php.net/rfc/expectations#namespaced_assert). Most likely I'll introduce a new function and make the existing one an alias to it so usage of assert() can be replaced in depending libraries.
